
development:
  adapter: mysql2
  database: tmca
  username: root
  password: 
  reconnect: true
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: tmca
  username: tmca_root
  password: 
  reconnect: true
  host: localhost
  pool: 5
  timeout: 5000
